# Generated by Django 4.1.2 on 2022-10-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_alter_hello_freqcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freqCardTarget', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Hello',
            new_name='MainDataBase',
        ),
        migrations.AlterModelOptions(
            name='maindatabase',
            options={},
        ),
    ]
