# Generated by Django 4.1.2 on 2022-10-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_configdatabase_rename_hello_maindatabase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configdatabase',
            name='freqCardTarget',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
