# Generated by Django 4.1.2 on 2022-10-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_alter_configdatabase_freqcardtarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configdatabase',
            name='freqCardTarget',
            field=models.IntegerField(default=0),
        ),
    ]
