# Generated by Django 4.1.2 on 2022-10-20 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_alter_configdatabase_freqcardtarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindatabase',
            name='freqCard',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
