# Generated by Django 4.1.2 on 2022-10-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_alter_maindatabase_freqcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='configdatabase',
            name='phraseMystere',
            field=models.CharField(default='', max_length=150),
        ),
    ]
