# Generated by Django 4.1.2 on 2022-10-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_configdatabase_phrasemystere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configdatabase',
            name='freqCardTarget',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
