# Generated by Django 4.1.7 on 2023-03-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_alter_configdatabase_freqcardtarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='passWordDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passWord', models.CharField(max_length=30)),
            ],
        ),
    ]
