# Generated by Django 4.1.7 on 2023-03-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_passworddb'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingWordsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=300)),
                ('yEnreg', models.CharField(max_length=1)),
                ('iDTexte', models.IntegerField(default=0)),
            ],
        ),
    ]
