# Generated by Django 4.1.7 on 2023-04-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_matchingwordsdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchingwordsdb',
            name='yEnreg',
        ),
        migrations.AddField(
            model_name='matchingwordsdb',
            name='reponse',
            field=models.CharField(default='', max_length=150),
        ),
    ]
