# Generated by Django 4.1.7 on 2023-04-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_remove_matchingwordsdb_yenreg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchingwordsdb',
            name='iDTexte',
        ),
    ]
